# Example GitHub Actions workflow for Percy
# Copy this to .github/workflows/percy.yml to enable CI/CD integration

name: Percy Visual Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  percy-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build application
      run: npm run build
    
    - name: Start application
      run: |
        npm start &
        sleep 10
        npx wait-on http://localhost:3000
      env:
        CI: true
    
    - name: Run Percy tests
      run: npm run e2e:screenshots:percy
      env:
        PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
        PERCY_BRANCH: ${{ github.head_ref || github.ref_name }}
        PERCY_PULL_REQUEST: ${{ github.event.pull_request.number }}
    
    - name: Upload Percy logs (on failure)
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: percy-logs
        path: |
          .percy/
          e2e/screenshots/

# Setup Instructions:
# 1. Create this file at: .github/workflows/percy.yml
# 2. Add PERCY_TOKEN to GitHub repository secrets:
#    - Go to: Settings → Secrets and variables → Actions
#    - Click "New repository secret"
#    - Name: PERCY_TOKEN
#    - Value: Your Percy token from https://percy.io/
# 3. Commit and push
# 4. Percy will run automatically on pushes and PRs
